spring.application.name=ezgloszenie

#wy??czenie flyway
#spring.flyway.enabled=false

#w??czenie hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql:localhost:5432/ezgloszeniedb
spring.datasource.username=myuser
spring.datasource.password=secret
